### PR TITLE
Properly escape html10n arguments in suggested change template

### LINKED ISSUE #175: Error while trying to add a suggestion with a quotation mark (or any special character)
## Context

* **OS**: Intel Mac OS X 10_14_6
* **Browser** : Mozilla/5.0, Chrome/86.0.4240.198
* **Etherpad** version: 1.8.6
* **ep_comments_page** version: 0.1.44

## Behavior

When adding a quote in a suggestion (`"` or `'`) an error occurs saying `Unexpected token in JSON at position`.
Seems like others special characters are having troubles too. (Tested : https://www.computerhope.com/jargon/s/specchar.htm )

## Steps to reproduce

Add a comment with a suggestion that contains quote mark

Capture d’écran 2020-12-10 à 09 51 34

## Failure Logs

When opening developer tools, console displays this error. It says that a token near 'F' is invalid. 

```
VM361:1 Uncaught SyntaxError: Unexpected token F in JSON at position 50
    at JSON.parse (<anonymous>)
    at Object.html10n.translateNode (html10n.js?v=54405fc9:1)
    at Object.html10n.translateElement (html10n.js?v=54405fc9:1)
    at Object.localize (eval at j (require-kernel.js?v=54405fc9:10), <anonymous>:5:41)
    at EpComments.insertComment (eval at j (require-kernel.js?v=54405fc9:10), <anonymous>:5:12443)
    at HTMLSpanElement.eval (eval at j (require-kernel.js?v=54405fc9:10), <anonymous>:5:9526)
    at Function.each (ace2_common.js?callback=require.define&v=54405fc9:27)
    at m.fn.init.each (ace2_common.js?callback=require.define&v=54405fc9:27)
    at EpComments.collectComments (eval at j (require-kernel.js?v=54405fc9:10), <anonymous>:5:9249)
    at r.eval (eval at j (require-kernel.js?v=54405fc9:10), <anonymous>:5:18760)
```

**Further investigation** : No problems when adding a simple comment with a quote.

## Failure image

Capture d’écran 2020-12-10 à 09 51 46

Then comment is broken and can't be displayed.

Capture d’écran 2020-12-10 à 09 52 43

**Special note**
Thank you for all you work on this project 😄

### LINKED ISSUE #211: Suggestion texts show %20 for space (also applies for other special characters)
**Describe the bug**
When adding a comment in English with a suggested change, any "special" character is shown in its percent-encoded form. For example a space is shown as %20, a bracket as %28.

**To Reproduce**
I added a comment while the pad was set English language with a suggested change.
I also noticed it in other languages like Spanish or French.
Interestingly enough, in German the suggested change was not shown at all. (see second screenshot)

**Expected behavior:**
normal text without encoded characters

**Screenshot:**
image
image

**Desktop** (please complete the following information):

OS: Windows 10
Browser: chrome
Version: 93

If you need more information, let me know.
Thank you!
Verena

### PR DESCRIPTION
**Pull request by Steffan153**
I removed the `escape()` call and instead used `JSON.stringify` in `index.js`, so the characters will be properly escaped, and quotation marks won't screw anything up and no XSS attacks can be done. I set a `changeArgs` variable that is passed to the template. This should fix #211 and fix #175.

### CODE REVIEW

File: static/js/index.js [hunk 1]
```diff
@@ -589,6 +589,7 @@ EpComments.prototype.insertComment = function (commentId, comment, index) {
 
   comment.commentId = commentId;
   comment.reply = true;
+  comment.changeArgs = JSON.stringify({changeFrom: comment.changeFrom, changeTo: comment.changeTo}).replace(/"/g, '&quot;');
   content = $('#commentsTemplate').tmpl(comment);
```
Comment (rhansen) [inline static/js/index.js:593]: I'm not very familiar with this plugin, but I'm a bit worried about mutating the caller's `comment` object. What do you think about this instead?

```suggestion
  content = $('#commentsTemplate').tmpl({
    ...comment,
    changeArgs: JSON.stringify({
      changeFrom: comment.changeFrom,
      changeTo: comment.changeTo,
    }).replace(/"/g, '&quot;'),
  });
```

Or maybe it would be better to let the browser handle escaping:

```suggestion
  content = $('#commentsTemplate').tmpl(comment);
  content.find('.from-label')[0].dataset.l10nArgs = JSON.stringify({
    changeFrom: comment.changeFrom,
    changeTo: comment.changeTo,
  });
```

**Comment by rhansen** [comment]
Thanks for this! Do you think you could add some tests?

File: templates/comments.html [hunk 2]
```diff
@@ -100,7 +100,7 @@ <h1 data-l10n-id="ep_comments_page.comment">Comment</h1>
           <!-- TODO: Fix below line to properly handle escaped characters -->
           <!-- Using escape() is a temp fix designed to handle suggestions to "foo" -->
           <!-- which historically would break a pad :( -->
```
Comment (rhansen) [inline templates/comments.html:102]: These comments can be deleted:

```suggestion
```

**Comment by Steffan153** [comment]
Yes, that's better. I'll add tests.

**Comment by bbernicker** [comment]
Hi @Steffan153. Any updates on this? Thanks for tackling this issue!

**Comment by Steffan153** [comment]
Sorry, forgot about this. How do you run the tests?

**Comment by rhansen** [comment]
> Sorry, forgot about this. How do you run the tests?

Start Etherpad and visit: `http://localhost:9001/tests/frontend/?grep=ep_comments_page`

I rebased your branch and pushed a couple of commits (including tests). If it looks OK to you I'll squash the commits together and merge.
